login tests, AddTrainingTest
MurzinaN/FinalSurge_Murzina_Natasha pull request #1
Opened 2022-08-28 10:40 UTC by MurzinaN

2022-08-28 18:12 UTC, voropa requested changes

2022-08-28 18:12 UTC, voropa commented on src/test/java/tests/AddTrainingTest.java
> +        workoutDetailsPage.getWorkoutQuickInfo();
Вероятно, это лишняя строчка кода тут

2022-08-28 18:12 UTC, voropa commented on src/test/java/tests/AddTrainingTest.java
> +        homePage.clickLogoutButton();
Если вы делаете в тесте login/logout и тест запускается несколько раз (data driven), то лучше вынести эти дейсьтвия в beforeMethod/afterMethod, чтобы гарантировано выполнялся login/logout

2022-08-28 18:12 UTC, voropa commented on src/test/java/utils/PresenceCheck.java
> +    public static boolean isElementPresent(By by) {
У вас же же есть метод isElementPresent в BasePage, зачем вам еще один тут?

2022-08-28 18:52 UTC, MurzinaN commented on src/test/java/tests/AddTrainingTest.java
> +        workoutDetailsPage.getWorkoutQuickInfo();
А какая именно, выделены 4?

2022-08-29 10:59 UTC, voropa commented on src/test/java/tests/AddTrainingTest.java
> +        workoutDetailsPage.getWorkoutQuickInfo();
39

2022-09-09 16:44 UTC, MurzinaN commented
У меня получилось 12 тестов, достаточно этого для диплома? И еще вопрос: т.к. у меня большинство тестов на создание объектов через builder, можно их в AfterMethod удалять после каждого теста, чтобы можно было потом запускать тесты по несколько раз подряд?

2022-09-09 18:52 UTC, voropa commented
> У меня получилось 12 тестов, достаточно этого для диплома? И еще вопрос: т.к. у меня большинство тестов на создание объектов через builder, можно их в AfterMethod удалять после каждого теста, чтобы можно было потом запускать тесты по несколько раз подряд?

Да, 12 тестов достаточно.
Удалять их не можно, а НУЖНО в after-методах, чтобы тесты были стабильными и независимыми

2022-09-12 08:55 UTC, voropa requested changes

2022-09-12 08:55 UTC, voropa commented on src/test/java/pages/ShoesPage.java
> +        System.out.println(brand);
?

2022-09-12 08:55 UTC, voropa commented on src/test/java/pages/ShoesPage.java
> +    public NewShoe getNewShoeInfo(String shoeName) {
Какая-то очень сложная и запутанная логика с парсингом строк у вас в этом классе. Давайте, вы на занятии покажете мне, что там за страница и какую информацию нужно с нее получать

2022-09-12 08:55 UTC, voropa commented on src/test/java/pages/WorkoutDetailsPage.java
> +        if (isElementPresentByLocator(WORKOUT_NAME_LOCATOR) == true) {
=== true здесь излишне, поскольку метод isElementPresentByLocator и так возвращает true/false

2022-09-13 17:57 UTC, merged